Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

#from cart.views import cartHome
from .views import home_page
from userApp.views import user_logout
urlpatterns = [
    # url(r'^$', include('homeApp.urls')),
    #path('cart/',cartHome,name='cart'),
    url(r'^$', home_page,name='home'),
    path('admin/', admin.site.urls),
    url(r'cart/',include('cart.urls',namespace='cart')),
    url(r'category/',include('categoryApp.urls',namespace='category')),
    url(r'^userApp/',include('userApp.urls')),
    url(r'^order/',include('order.urls')),
    url(r'^logout/$',user_logout, name='logout'),
    url(r'^search/', include("search.urls", namespace='search')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url

from .views import cartHome,cartUpdate

app_name='cart'
urlpatterns=[
    url(r'^$',cartHome,name='cartHome'),
    url(r'^update/$',cartUpdate,name='cartUpdate'),
]

userApp/urls.py
from django.conf.urls import url
from userApp import views

# SET THE NAMESPACE!
app_name = 'userApp'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

templates/home/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"> </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% block style_block %}

{% endblock %}
    <title>GO</title>

  </head>
  <body>

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
      <a class="navbar-brand" href='{% url 'home' %}'>E-Commerce</a>
        </div>
        <ul class="nav navbar-nav">

      <li class="dropdown">
       <a class="dropdown-toggle" data-toggle="dropdown" href="#">Electronics
       <span class="caret"></span></a>
       <ul class="dropdown-menu">
         <li><a href="/search/?q=smartphone">SmartPhones</a></li>
         <li><a href="/search/?q=laptop">Laptops</a></li>
         <li><a href="/search/?q=tv">TVs</a></li>
       </ul>
     </li>

     <li class="dropdown">
       <a class="dropdown-toggle" data-toggle="dropdown" href="#">Fashion
       <span class="caret"></span></a>
       <ul class="dropdown-menu">
         <li><a href="#">Male</a></li>
         <li><a href="#">Female</a></li>
         <li><a href="#">Kids</a></li>
       </ul>
     </li>
     <li class="dropdown">
       <a class="dropdown-toggle" data-toggle="dropdown" href="#">Sports
       <span class="caret"></span></a>
       <ul class="dropdown-menu">
         <li><a href="#">Cricket</a></li>
         <li><a href="#">Hockey</a></li>
         <li><a href="#">Football</a></li>
       </ul>
     </li>
     <li class="dropdown">
       <a class="dropdown-toggle" data-toggle="dropdown" href="#">Entertainment
       <span class="caret"></span></a>
       <ul class="dropdown-menu">
         <li><a href="#">Music</a></li>
         <li><a href="#">Video Games</a></li>
         <li><a href="#">Dance</a></li>
       </ul>
     </li>
    </ul>
        </ul>
        <form class="navbar-form navbar-left" action="/search">
      <div class="form-group">
        <input type="text" class="form-control" name="q" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      {% else %}
      <li><a href="{% url 'userApp:register' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'userApp:user_login' %}?next={{request.build_absolute_uri }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endif %}
    </ul>
    <a href="{% url 'cart:cartHome' %}" class="btn btn-info btn-lg">
         <span class="glyphicon glyphicon-shopping-cart"></span>Cart</a>
      </div>
    </nav>
{% block body_block %}
{% endblock %}
  </body>
</html>

templates/home/index.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{%  load staticfiles %}
{% block style_block %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 500px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 200px) {
  .text {font-size: 11px}
}
</style>
{% endblock %}
{% block body_block%}
<body>

<div class="slideshow-container">

<div class="mySlides fade">
  <div class="numbertext">1 / 3</div>
  <img src="{% static "images/r1.png" %}" style="width:100%">
  <div class="text">Caption Text</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">2 / 3</div>
  <img src="{% static "images/r.png" %}" style="width:100%">
  <div class="text">Caption Two</div>
</div>

<div class="mySlides fade">
  <div class="numbertext">3 / 3</div>
  <img src="{% static "images/r2.jpeg" %}" style="width:100%">
  <div class="text">Caption Three</div>
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
</div>

<script>
var slideIndex = 0;
showSlides();

function showSlides() {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    for (i = 0; i < slides.length; i++) {
       slides[i].style.display = "none";
    }
    slideIndex++;
    if (slideIndex > slides.length) {slideIndex = 1}
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
    setTimeout(showSlides, 3000); // Change image every 2 seconds
}
</script>

{% endblock%}

templates/home/temp.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{%  load staticfiles %}
{% block body_block %}
<div class="w3-content w3-section" style="max-width:500px">
  <img class="mySlides" src="{% static "images/r.png" %}" style="width:100%">
  <img class="mySlides" src="{% static "images/r1.png" %}" style="width:70%">
  <img class="mySlides" src="{% static "images/r2.jpeg" %}" style="width:100%">
</div>

<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}
    x[myIndex-1].style.display = "block";
    setTimeout(carousel, 2000); // Change image every 2 seconds
}
</script>
{% endblock%}