Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

#from cart.views import cartHome
from .views import home_page
from userApp.views import user_logout
urlpatterns = [
    # url(r'^$', include('homeApp.urls')),
    #path('cart/',cartHome,name='cart'),
    url(r'^$', home_page,name='home'),
    path('admin/', admin.site.urls),
    url(r'cart/',include('cart.urls',namespace='cart')),
    url(r'category/',include('categoryApp.urls',namespace='category')),
    url(r'^userApp/',include('userApp.urls')),
    url(r'^order/',include('order.urls')),
    url(r'^logout/$',user_logout, name='logout'),
    url(r'^search/', include("search.urls", namespace='search')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url

from .views import cartHome,cartUpdate

app_name='cart'
urlpatterns=[
    url(r'^$',cartHome,name='cartHome'),
    url(r'^update/$',cartUpdate,name='cartUpdate'),
]

categoryApp/urls.py
from django.conf.urls import url

from .views import (
        ProductListView,
        ProductDetailSlugView,
        )
app_name='category'
urlpatterns = [
    url(r'^$', ProductListView.as_view(),name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(),name='detail'),
]

categoryApp/models.py
import random
import os
from django.db import models
from django.db.models.signals import pre_save, post_save

from django.urls import reverse
from .utils import unique_slug_generator



class Product(models.Model):
    title           = models.CharField(max_length=120)
    company         = models.CharField(max_length=120,null=True)
    model           = models.CharField(max_length=200,unique=True,null=True)
    slug            = models.SlugField(blank=True, unique=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
    image           = models.ImageField(upload_to='image', null=True, blank=True)



    def get_absolute_url(self):
        #return "/category/{slug}/".format(slug=self.slug)
         return reverse("category:detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product)

categoryApp/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404

from cart.models import Cart
from .models import Product



class ProductListView(ListView):
    template_name = "categoryApp/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()


def product_list_view(request):
    queryset = Product.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "categoryApp/list.html", context)



class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "categoryApp/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj,new_obj=Cart.objects.newCart_or_getCart(self.request)
        context['cart']=cart_obj
        print('pp')
        print(context['cart'])
        print('pp')
        return context


    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        #instance = get_object_or_404(Product, slug=slug, active=True)
        try:
            instance = Product.objects.get(slug=slug)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug)
            instance = qs.first()
    #    except:
    #        raise Http404("Uhhmmm ")
        return instance



class ProductDetailView(DetailView):
    #queryset = Product.objects.all()
    template_name = "categoryApp/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        # context['abc'] = 123
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Product doesn't exist")
        return instance

    # def get_queryset(self, *args, **kwargs):
    #     request = self.request
    #     pk = self.kwargs.get('pk')
    #     return Product.objects.filter(pk=pk)


def product_detail_view(request, pk=None, *args, **kwargs):
    # instance = Product.objects.get(pk=pk, featured=True) #id
    # instance = get_object_or_404(Product, pk=pk, featured=True)
    # try:
    #     instance = Product.objects.get(id=pk)
    # except Product.DoesNotExist:
    #     print('no product here')
    #     raise Http404("Product doesn't exist")
    # except:
    #     print("huh?")

    instance = Product.objects.get_by_id(pk)
    if instance is None:
        raise Http404("Product doesn't exist")
    #print(instance)
    # qs  = Product.objects.filter(id=pk)

    # #print(qs)
    # if qs.exists() and qs.count() == 1: # len(qs)
    #     instance = qs.first()
    # else:
    #     raise Http404("Product doesn't exist")

    context = {
        'object': instance
    }
    return render(request, "categoryApp/detail.html", context)

categoryApp/templates/categoryApp/detail.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block body_block %}
<div class='row'>
  <div class='col-12 col-md-6'>
    <h1>{{ object.title }}</h1> <br/>
    <h1>{{ object.company }}</h1> <br/>
    {{ object.description }} <br/>
    {% if object.image %}
    <img src='{{ object.image.url }}' class='img-fluid' />
    {% endif %}
  </div>
  <div class='col-12 col-md-6'>
    {% include 'categoryApp/update_cart.html' with product=object cart=cart %}
  </div>
</div>
{% endblock %}

categoryApp/templates/categoryApp/list.html
<!DOCTYPE html>
{% extends "home/base.html" %}
{%  load staticfiles %}
{% block style_block %}
  <style>
  footer {
        background-color: #f2f2f2;
        padding: 25px;
      }
  </style>
{% endblock %}
{% block body_block %}
<div class="container">

  <div class="row">
    {% if object_list %}
       {% for acc in object_list %}
    <div class="col-sm-4">
      <div class="panel panel-primary">

        <div class="panel-heading"><h3>Company{{ acc.company }}<br/></h3> <h3>Model {{ acc.model }}</h3></div>
        {% if acc.image %}

          <div class="panel-body"><a href='{{ acc.get_absolut_url }}'><img src="{{ acc.image.url }}" class="img-responsive" style="width:100%" alt="Image"></a></div>
        {% endif %}
        <div class="panel-footer"><h3>Price--${{acc.price}}</h3> </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <p>Not found: empty</p>
    {% endif %}
  </div>

</div>
{% endblock %}

categoryApp/templates/categoryApp/update_cart.html
<form class="form" action="{% url 'cart:cartUpdate' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="product_id" value="{{ product.id }}"/>
  {% if in_cart %}
    <button type="submit" class="btn btn-link" style="padding:0px; cursor:pointer;">Remove</button>
  {% else %}
    {% if product in cart.products.all %}
    In Cart <button type="submit" class="btn btn-link">Remove</button>
    {% else %}
    <button type="submit" class="btn btn-success">Add to Cart</button>
    {% endif %}
  {% endif %}
</form>