Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

#from cart.views import cartHome
from .views import home_page
from userApp.views import user_logout
urlpatterns = [
    # url(r'^$', include('homeApp.urls')),
    #path('cart/',cartHome,name='cart'),
    url(r'^$', home_page,name='home'),
    path('admin/', admin.site.urls),
    url(r'cart/',include('cart.urls',namespace='cart')),
    url(r'category/',include('categoryApp.urls',namespace='category')),
    url(r'^userApp/',include('userApp.urls')),
    url(r'^order/',include('order.urls')),
    url(r'^logout/$',user_logout, name='logout'),
    url(r'^search/', include("search.urls", namespace='search')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url

from .views import cartHome,cartUpdate

app_name='cart'
urlpatterns=[
    url(r'^$',cartHome,name='cartHome'),
    url(r'^update/$',cartUpdate,name='cartUpdate'),
]

order/urls.py
from django.conf.urls import url
from .views import createOrder,setAddress
app_name='order'

urlpatterns=[
    url(r'^create_order/$',createOrder,name='createOrder'),
    url(r'^deliver_to/$',setAddress,name='setAddress'),
]

order/models.py
from django.db import models
from cart.models import Cart
from categoryApp.utils import unique_order_id_generator
from django.db.models.signals import pre_save,post_save
# Create your models here.
ORDER_STATUS_CHOICES = (
    ('created', 'Created'),
    ('paid', 'Paid'),
    ('shipped', 'Shipped'),
)
class Order(models.Model):
    order_id = models.CharField(max_length=120,blank=True)
    cart = models.OneToOneField(Cart,on_delete=models.CASCADE,null=True,blank=True)
    status = models.CharField(max_length=120,default='created',choices=ORDER_STATUS_CHOICES)
    total = models.DecimalField(default=0.00,max_digits=100,decimal_places=2)
    address = models.CharField(max_length=120,blank=True)

    def __str__(self):
        return self.order_id

    def update_total(self):
        cart_total=self.cart.total
        self.total=cart_total
        self.save()
        return cart_total

def pre_save_create_order_id(sender,instance,*args,**kwargs):
    if not instance.order_id:
        instance.order_id = unique_order_id_generator(instance)

pre_save.connect(pre_save_create_order_id,sender=Order)

def post_save_order(sender,instance,created,*args,**kwargs):
    if created:
        instance.total=instance.update_total()
        instance.save()
        #print("ch")
        print(instance.total)

post_save.connect(post_save_order,sender=Order)

def post_save_cart_total(sender,instance,created,*args,**kwargs):
    if not created:
        #print("f")
        print(instance.id)
        qs=Order.objects.filter(cart__id=instance.id)
        if qs.count()==1:
            qs.first().update_total()
            qs.first().save()

post_save.connect(post_save_cart_total,sender=Cart)

order/forms.py
from django import forms

from .models import Order

class AddressForm(forms.ModelForm):
    class Meta:
        model = Order
        fields=[
            'address',
        ]

order/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import Order
from cart.models import Cart
from userApp.models import UserProfileInfo
# Create your views here.
def createOrder(request):
    if request.user.is_authenticated:
        cart_obj=Cart.objects.filter(user=request.user,active=True).first()
        print(cart_obj)
        order_obj=Order.objects.filter(cart=cart_obj).first()
        #print("hehehe")
        print(order_obj)
        user_info=UserProfileInfo.objects.filter(user=request.user).first()
        print(user_info)
        if order_obj is None:
            Order.objects.create(cart=cart_obj)
        return render(request,"order/checkout.html",{'cart_obj':cart_obj,'order_obj':order_obj,'user_info':user_info})
    else:
        return render(request, 'userApp/login.html', {'redirect_url':request.build_absolute_uri })

def setAddress(request):
    address=request.POST.get('address')
    print("papa")
    order_id=request.POST.get('order_id')
    print(order_id)
    order_obj=Order.objects.filter(order_id=order_id).first()
    order_obj.address=address
    print(request.POST.get('updateAddress'))
    order_obj.save()
    if request.POST.get('updateAddress') is not None:
        user_obj=UserProfileInfo.objects.filter(user=request.user).first()
        user_obj.address=order_obj.address
        user_obj.save()
    return render(request,'order/payment.html',{})

order/templates/order/checkout.html
{% extends "home/base.html" %}
{% block body_block %}
<h1>Soon, We will add the feature of payment!</h1>
<h2>{{order_obj}}</h2>
<h2>{{cart_obj}}</h2>
<h2>{{cart_obj.user.username}}</h2>
<h2>{{order_obj.address}}</h2>
<form class="form-horizontal" action="{% url 'order:setAddress' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="order_id" value="{{order_obj}}"/>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Order Delivery Address:</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="address" id="email" placeholder="Enter Delivery Address">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label><input name="updateAddress" type="checkbox"> Update Profile Address </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

order/templates/order/payment.html
{% extends "home/base.html" %}
{% block body_block %}
<h1>Soon, We will add the feature of payment!</h1>
{% endblock %}